#!/bin/sh
set -e

# =============================================================================
# eovpanel frontend entrypoint
# =============================================================================
# Generates the nginx configuration at startup so the deployment can be
# parameterized at container runtime:
#   - BASE_PATH (optional): when set (e.g. /dashboard), the whole panel —
#     SPA routes, /api and /sub — is served under that prefix and everything
#     else returns 404, hiding the panel from internet scanners.
#   - TLS: enabled automatically when certs are mounted to /etc/nginx/ssl/.
# =============================================================================

BASE_PATH="${BASE_PATH:-}"
if [ -n "$BASE_PATH" ]; then
    case "$BASE_PATH" in /*) ;; *) BASE_PATH="/$BASE_PATH";; esac
    BASE_PATH="${BASE_PATH%/}"
fi

TLS_CERT="/etc/nginx/ssl/fullchain.pem"
TLS_KEY="/etc/nginx/ssl/privkey.pem"

if [ -f "$TLS_CERT" ] && [ -f "$TLS_KEY" ]; then
    TLS="1"
    echo "[entrypoint] TLS certificates found — enabling HTTPS on port 443"
else
    TLS=""
    echo "[entrypoint] No TLS certificates found — running HTTP only on port 80"
fi

if [ -n "$BASE_PATH" ]; then
    echo "[entrypoint] Panel base path: $BASE_PATH (hidden deployment)"
else
    echo "[entrypoint] Panel base path: / (default)"
fi

CONF="/etc/nginx/conf.d/default.conf"

cat > "$CONF" << EOF
# =============================================================================
# eovpanel frontend — generated by entrypoint.sh at container start
# Base path: '${BASE_PATH:-/}'   TLS: $([ -n "$TLS" ] && echo yes || echo no)
# =============================================================================

gzip on;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_min_length 256;
gzip_types text/plain text/css text/xml text/javascript
           application/json application/javascript application/xml
           application/rss+xml application/atom+xml image/svg+xml;
EOF

if [ -n "$TLS" ]; then
    cat >> "$CONF" << 'EOF'
# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
EOF
else
    cat >> "$CONF" << 'EOF'
server {
    listen 80;
    server_name _;
EOF
fi

if [ -n "$BASE_PATH" ]; then
    # ------------------------------------------------------------------- #
    # Hidden deployment — panel reachable only under $BASE_PATH.           #
    # Everything outside the prefix returns 404 (scanners get nothing).    #
    # /api and /sub are proxied to the backend with the prefix stripped.   #
    # ------------------------------------------------------------------- #
    cat >> "$CONF" << EOF
    root /usr/share/nginx/html;
    index index.html;

    # Tell the SPA its base path at runtime
    sub_filter '</head>' '</head><script>window.__APP_BASE_PATH__="$BASE_PATH";</script>';
    sub_filter_once on;
    sub_filter_types text/html;

    # Hide everything outside the base path
    location / {
        return 404;
    }

    # The SPA shell itself — internal target for the fallback below
    location = /index.html {
        try_files index.html =404;
    }

    # SPA shell + routes (fall back to index.html, sub_filter injects path)
    location $BASE_PATH {
        try_files \$uri \$uri/ /index.html;
    }

    # Static assets (loaded by the SPA shell)
    location /assets/ {
        try_files \$uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location = /favicon.svg {
        add_header Cache-Control "public, max-age=86400";
        try_files \$uri =404;
    }

    # Reverse proxy to backend API (prefix stripped)
    location $BASE_PATH/api/ {
        rewrite ^$BASE_PATH(/api/.*)\$ \$1 break;
        proxy_pass http://backend:8000;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Port \$server_port;
        proxy_read_timeout 300s;
        proxy_connect_timeout 60s;
    }

    # Public subscription endpoint (prefix stripped)
    location $BASE_PATH/sub/ {
        rewrite ^$BASE_PATH(/sub/.*)\$ \$1 break;
        proxy_pass http://backend:8000;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Port \$server_port;
        proxy_read_timeout 300s;
        proxy_connect_timeout 60s;
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://api.qrserver.com; font-src 'self'; connect-src 'self'; frame-ancestors 'self';" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
}
EOF
else
    # ------------------------------------------------------------------- #
    # Default deployment — panel served at the root.                      #
    # ------------------------------------------------------------------- #
    cat >> "$CONF" << 'EOF'
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback — all unmatched routes serve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy to backend API
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_read_timeout 300s;
        proxy_connect_timeout 60s;
    }

    # Public subscription endpoint (no auth)
    location /sub/ {
        proxy_pass http://backend:8000/sub/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_read_timeout 300s;
        proxy_connect_timeout 60s;
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://api.qrserver.com; font-src 'self'; connect-src 'self'; frame-ancestors 'self';" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
EOF
fi

# Validate the generated config before starting nginx
nginx -t -c /etc/nginx/nginx.conf >/dev/null

# Start nginx in foreground
exec nginx -g "daemon off;"